source 'https://rubygems.org'
ruby '2.3.1'

gem 'httparty'
gem 'activerecord'
gem 'pg'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'rake'
  gem 'rspec'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'selenium-webdriver'
end